/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns;

import org.junit.Test;

import static org.junit.Assert.*;

import design.patterns.Library;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
